[[language]]
name = "haskell"
auto-format = true

[[language]]
name = "ocaml"
auto-format = true

# TODO make this work
[[language]]
name = "toml"
auto-format = true

[[language]]
name = "rust"
[language.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
'<' = '>'

[[language]]
name = "kast"
file-types = ["ks"]
scope = "source.ks"
language-servers = ["kast-lsp"]

[language-server.rust-analyzer.config]
cargo.features = "all"
check = { command = "clippy" }

[language-server.haskell-language-server]
config.haskell.plugin.rename = { config = { crossModule = true }}

[language-server.kast-lsp]
command = "kast"
args = ["lsp"]
